import { Lead, EmailSequenceLog, Notification, DashboardStats } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    created_at: "2026-03-28T10:15:00Z",
    full_name: "Marcus Thompson",
    first_name: "Marcus",
    email: "marcus.t@gmail.com",
    phone: "(503) 555-0142",
    state: "Oregon",
    riding_goal: "Recreation & fitness",
    height: "5'10\"",
    weight: "175 lbs",
    inquiry_type: "veteran",
    status: "replied",
    temperature: "hot",
    source: "website",
    assigned_to: "forrest",
    notes: "VA eligible, very interested in the sport model. Wants to try before buying.",
    tags: ["veteran", "hot"],
    email_sequence_active: false,
    email_sequence_step: 2,
    email_sequence_paused_at: "2026-03-30T14:00:00Z",
    last_contacted_at: "2026-03-31T09:00:00Z",
    last_replied_at: "2026-03-30T14:00:00Z",
  },
  {
    id: "lead-002",
    created_at: "2026-03-29T14:30:00Z",
    full_name: "Sarah Chen",
    first_name: "Sarah",
    email: "sarah.chen@outlook.com",
    phone: "(415) 555-0198",
    state: "California",
    riding_goal: "Competitive racing",
    height: "5'6\"",
    weight: "130 lbs",
    inquiry_type: "general",
    status: "contacted",
    temperature: "medium",
    source: "ad",
    assigned_to: "",
    notes: "",
    tags: ["ad lead"],
    email_sequence_active: true,
    email_sequence_step: 1,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-03-29T14:35:00Z",
    last_replied_at: null,
  },
  {
    id: "lead-003",
    created_at: "2026-03-30T09:45:00Z",
    full_name: "James Rivera",
    first_name: "James",
    email: "jrivera@yahoo.com",
    phone: "(720) 555-0167",
    state: "Colorado",
    riding_goal: "Daily transportation",
    height: "6'1\"",
    weight: "200 lbs",
    inquiry_type: "general",
    status: "new",
    temperature: "medium",
    source: "website",
    assigned_to: "",
    notes: "",
    tags: [],
    email_sequence_active: true,
    email_sequence_step: 1,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-03-30T09:50:00Z",
    last_replied_at: null,
  },
  {
    id: "lead-004",
    created_at: "2026-03-25T16:20:00Z",
    full_name: "Patricia Williams",
    first_name: "Patricia",
    email: "pat.w@gmail.com",
    phone: "(206) 555-0134",
    state: "Washington",
    riding_goal: "Recreation & fitness",
    height: "5'4\"",
    weight: "145 lbs",
    inquiry_type: "general",
    status: "qualified",
    temperature: "hot",
    source: "referral",
    assigned_to: "bob",
    notes: "Referred by existing customer. Ready to purchase, discussing sizing.",
    tags: ["bob's lead", "hot"],
    email_sequence_active: false,
    email_sequence_step: 3,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-04-01T10:00:00Z",
    last_replied_at: "2026-03-31T18:00:00Z",
  },
  {
    id: "lead-005",
    created_at: "2026-03-27T11:00:00Z",
    full_name: "David Kim",
    first_name: "David",
    email: "dkim@gmail.com",
    phone: "(503) 555-0189",
    state: "Oregon",
    riding_goal: "Competitive racing",
    height: "5'9\"",
    weight: "160 lbs",
    inquiry_type: "veteran",
    status: "closed_won",
    temperature: "hot",
    source: "ad",
    assigned_to: "bob",
    notes: "Purchased sport model. VA funding approved.",
    tags: ["veteran", "ad lead", "bob's lead"],
    email_sequence_active: false,
    email_sequence_step: 3,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-04-02T09:00:00Z",
    last_replied_at: "2026-04-01T15:00:00Z",
  },
  {
    id: "lead-006",
    created_at: "2026-04-01T08:30:00Z",
    full_name: "Emily Foster",
    first_name: "Emily",
    email: "emily.foster@gmail.com",
    phone: "(971) 555-0156",
    state: "Oregon",
    riding_goal: "Recreation & fitness",
    height: "5'7\"",
    weight: "155 lbs",
    inquiry_type: "general",
    status: "new",
    temperature: "cold",
    source: "website",
    assigned_to: "",
    notes: "",
    tags: [],
    email_sequence_active: true,
    email_sequence_step: 0,
    email_sequence_paused_at: null,
    last_contacted_at: null,
    last_replied_at: null,
  },
  {
    id: "lead-007",
    created_at: "2026-04-01T15:45:00Z",
    full_name: "Robert Martinez",
    first_name: "Robert",
    email: "rmartinez@hotmail.com",
    phone: "(480) 555-0123",
    state: "Arizona",
    riding_goal: "Daily transportation",
    height: "5'11\"",
    weight: "185 lbs",
    inquiry_type: "veteran",
    status: "contacted",
    temperature: "medium",
    source: "ad",
    assigned_to: "",
    notes: "Interested in VA funding options",
    tags: ["veteran", "ad lead"],
    email_sequence_active: true,
    email_sequence_step: 2,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-04-02T09:00:00Z",
    last_replied_at: null,
  },
  {
    id: "lead-008",
    created_at: "2026-03-20T12:00:00Z",
    full_name: "Linda Johnson",
    first_name: "Linda",
    email: "linda.j@aol.com",
    phone: "(541) 555-0178",
    state: "Oregon",
    riding_goal: "Recreation & fitness",
    height: "5'3\"",
    weight: "140 lbs",
    inquiry_type: "general",
    status: "closed_lost",
    temperature: "cold",
    source: "website",
    assigned_to: "",
    notes: "Budget concerns — may revisit later",
    tags: [],
    email_sequence_active: false,
    email_sequence_step: 3,
    email_sequence_paused_at: null,
    last_contacted_at: "2026-03-28T10:00:00Z",
    last_replied_at: "2026-03-26T16:00:00Z",
  },
  {
    id: "lead-009",
    created_at: "2026-04-02T10:00:00Z",
    full_name: "Michael Brown",
    first_name: "Michael",
    email: "mbrown@gmail.com",
    phone: "(303) 555-0145",
    state: "Colorado",
    riding_goal: "Competitive racing",
    height: "6'0\"",
    weight: "180 lbs",
    inquiry_type: "general",
    status: "new",
    temperature: "medium",
    source: "ad",
    assigned_to: "",
    notes: "",
    tags: ["ad lead"],
    email_sequence_active: true,
    email_sequence_step: 0,
    email_sequence_paused_at: null,
    last_contacted_at: null,
    last_replied_at: null,
  },
  {
    id: "lead-010",
    created_at: "2026-04-02T16:30:00Z",
    full_name: "Jennifer Adams",
    first_name: "Jennifer",
    email: "jen.adams@gmail.com",
    phone: "(458) 555-0190",
    state: "Oregon",
    riding_goal: "Recreation & fitness",
    height: "5'5\"",
    weight: "135 lbs",
    inquiry_type: "general",
    status: "new",
    temperature: "medium",
    source: "website",
    assigned_to: "",
    notes: "",
    tags: [],
    email_sequence_active: true,
    email_sequence_step: 0,
    email_sequence_paused_at: null,
    last_contacted_at: null,
    last_replied_at: null,
  },
];

export const mockEmailLogs: EmailSequenceLog[] = [
  { id: "el-001", lead_id: "lead-001", step: 1, sent_at: "2026-03-28T10:20:00Z", email_subject: "Thanks for Reaching Out!", status: "opened" },
  { id: "el-002", lead_id: "lead-001", step: 2, sent_at: "2026-03-31T10:00:00Z", email_subject: "Following Up — Freedom Ryder", status: "replied" },
  { id: "el-003", lead_id: "lead-002", step: 1, sent_at: "2026-03-29T14:35:00Z", email_subject: "Thanks for Reaching Out!", status: "delivered" },
  { id: "el-004", lead_id: "lead-003", step: 1, sent_at: "2026-03-30T09:50:00Z", email_subject: "Thanks for Reaching Out!", status: "opened" },
  { id: "el-005", lead_id: "lead-004", step: 1, sent_at: "2026-03-25T16:25:00Z", email_subject: "Thanks for Reaching Out!", status: "opened" },
  { id: "el-006", lead_id: "lead-004", step: 2, sent_at: "2026-03-28T16:00:00Z", email_subject: "Following Up — Freedom Ryder", status: "opened" },
  { id: "el-007", lead_id: "lead-004", step: 3, sent_at: "2026-04-01T10:00:00Z", email_subject: "One Last Thing — Freedom Ryder", status: "replied" },
  { id: "el-008", lead_id: "lead-005", step: 1, sent_at: "2026-03-27T11:05:00Z", email_subject: "VA Funding & Handcycle Info", status: "opened" },
  { id: "el-009", lead_id: "lead-005", step: 2, sent_at: "2026-03-30T11:00:00Z", email_subject: "Following Up — Freedom Ryder", status: "replied" },
  { id: "el-010", lead_id: "lead-007", step: 1, sent_at: "2026-04-01T15:50:00Z", email_subject: "VA Funding & Handcycle Info", status: "opened" },
  { id: "el-011", lead_id: "lead-007", step: 2, sent_at: "2026-04-02T09:00:00Z", email_subject: "Following Up — Freedom Ryder", status: "sent" },
];

export const mockNotifications: Notification[] = [
  { id: "n-001", created_at: "2026-04-02T16:30:00Z", type: "new_lead", title: "New Lead", message: "Jennifer Adams submitted the website form", read: false, lead_id: "lead-010" },
  { id: "n-002", created_at: "2026-04-02T10:00:00Z", type: "new_lead", title: "New Lead", message: "Michael Brown submitted the website form", read: false, lead_id: "lead-009" },
  { id: "n-003", created_at: "2026-04-01T15:00:00Z", type: "reply", title: "Lead Replied", message: "David Kim replied to the follow-up email", read: true, lead_id: "lead-005" },
  { id: "n-004", created_at: "2026-04-01T10:00:00Z", type: "sequence_complete", title: "Sequence Complete", message: "Patricia Williams completed the 3-email sequence — handed off to Bob", read: true, lead_id: "lead-004" },
  { id: "n-005", created_at: "2026-03-30T14:00:00Z", type: "reply", title: "Lead Replied", message: "Marcus Thompson replied to the follow-up email", read: true, lead_id: "lead-001" },
];

export const mockStats: DashboardStats = {
  total_leads: 10,
  new_leads_this_week: 4,
  active_sequences: 4,
  ad_leads: 4,
  conversions: 1,
  roas_ratio: 25,
  leads_by_status: {
    new: 4,
    contacted: 2,
    replied: 1,
    qualified: 1,
    closed_won: 1,
    closed_lost: 1,
  },
  leads_by_temperature: {
    hot: 3,
    medium: 5,
    cold: 2,
  },
};
